included:
    - yellowCard/Sources
excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Pods
disabled_rules:
#  - colon
#  - comma
#  - control_statement
    - file_length
#  - force_cast
#  - force_try
#  - function_body_length
#  - leading_whitespace
    - line_length
    - nesting
#  - opening_brace
#  - operator_whitespace
#  - return_arrow_whitespace
#  - statement_position
    - todo
#  - trailing_newline
#  - trailing_semicolon
#  - trailing_whitespace
    - type_body_length
#  - type_name
#  - variable_name_max_length
#  - variable_name_min_length
#  - variable_name
    - cyclomatic_complexity
    - identifier_name
    - empty_enum_arguments

type_name:
    min_length: 4 # only warning
    max_length: # warning and error
        warning: 40
        error: 80
    excluded: # excluded via string
        - T
# 함수의 매개변수 갯수를 제한합니다.
function_parameter_count:
    warning: 8
    error: 10
identifier_name:
    min_length: 2
