# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yellowCard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for yellowCard
  pod 'Kingfisher',     '4.10.1'
  pod 'ObjectMapper',   '~> 3.4'
  pod 'RxSwift',        '~> 4.0'
  pod 'RxCocoa',        '~> 4.0'
  pod 'SnapKit',        '~> 4.0.0'
  pod 'Alamofire',      '~> 5.0.0.beta.1'
  pod 'Then'

  pod 'lottie-ios'
  pod 'PopupDialog', '~> 0.9'

  # login SDK
  pod 'GoogleSignIn'

end

#post_install do |installer|
#    if ['PopupDialog'].include? target.name
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.2'
#        end
#        else
#        target.build_configurations.each do |config|
#            config.build_settings['SWIFT_VERSION'] = '4.0'
#        end
#    end
#end
