# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'yellowCard' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'Then'
  pod 'Kingfisher',     '4.10.1'
  pod 'ObjectMapper',   '~> 3.4'

end
